model:
  base_learning_rate: 5e-5
  target: ldm.models.diffusion.ddpm.AutoDM
  params: 
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    cond_stage_key: "image"
    image_size: (1600,900)
    channels: 3
    cond_stage_trainable: False
    scale_by_std: True
    monitor: 'val/loss_simple_ema'
    unet_trainable: True
    cond_stage_config: 
        target: __is_unconditional__

    scheduler_config: #10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UnetModel
      params:
        image_size: (1600,900)
        in_channels: 8
        out_channels: 8
        model_channels: 192
        attention_resolutions: [1,2,4,8] #32 16 8 4
        num_res_blocks: 2
        channel_mult: [1,2,2,4,4] #32,16,8,4,2
        num_heads: 8
        use_scale_shift_norm: True
        resblock_updown: True
        context_dim: 768
        use_spatial_transformer: True
      
    ref_img_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path:
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 4
          ch: 4
          ch_mult: [1,1,2] #num_down=len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          num_groups: 4
        lossconfig:
          target: torch.nn.Identity
    
    hdmap_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path:
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 4
          out_ch: 4
          ch: 4
          ch_mult: [1,1,2]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          num_groups: 4
        lossconfig:
          target: torch.nn.Identity
    box_config:
      target: ldm.models.autoencoder.Fourier_Embedding
      params:
        in_channels: 16
        ch: [256,512,768]
        context_dims: 768
        sigma: 1
        trainable: True


data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    num_workers: 0
    wrap: False
    train:
      target: ldm.data.lsun.LSUNChurchesTrain
      params:
        size: 256
        num_boxes: 50
        cond_stage_config: 
          target: ldm.models.autoencoder.FrozenCLIPTextEmbedder
    validation:
      target: ldm.data.lsun.LSUNChurchesValidation
      params:
        size: 256
        num_boxes: 50
        cond_stage_config: 
          target: ldm.models.autoencoder.FrozenCLIPTextEmbedder

lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
    gpus: 0,

    