model:
  base_learning_rate: 5e-6
  target: ldm.models.diffusion.ddpm.AutoDM_PretrainedAutoEncoder
  params:
    base_learning_rate: 5e-6
    linear_start: 0.0015
    linear_end: 0.0155
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    loss_type: l1
    cond_stage_key: "image"
    image_size: [16,32]
    channels: 4
    cond_stage_trainable: True
    scale_by_std: True
    monitor: 'val/loss_simple'
    unet_trainable: True
    learn_logvar: True
    movie_len: 5
    cond_stage_config: 
        target: ldm.models.autoencoder.FrozenCLIPTextEmbedder

    scheduler_config: #10000 warmup steps
      target: ldm.lr_scheduler.LambdaLinearScheduler
      params:
        warm_up_steps: [10000]
        cycle_lengths: [10000000000000]
        f_start: [1.e-6]
        f_max: [1.]
        f_min: [1.]
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: [16,32]
        in_channels: 8
        out_channels: 4
        model_channels: 320
        attention_resolutions: [1,2,4] #32 16 8 4
        num_res_blocks: 2
        channel_mult: [1,2,4,4] #32,16,8,4,2
        num_heads: 8
        use_scale_shift_norm: False
        resblock_updown: False
        context_dim: 768
        use_checkpoint: False
        use_spatial_transformer: True
        # ckpt_path: stable_diffusion/sd-v1-4.ckpt
        ckpt_path: logs/2024-07-20T22-19-28_first_stage_step1_config_mini/checkpoints/last.ckpt
        movie_len: 5
        height: 16
        width: 32
        obj_dims: 768
        outpadding: [[0,0],[0,0],[0,0]]
        # ignore_keys: ['model.diffusion_model.input_blocks.0.0','model.diffusion_model.out.2','cond_stage_model']
        ignore_keys: ['temporal_blocks']
        # ignore_keys: ['model.diffusion_model.input_blocks.0.0']

      
    ref_img_config:
      target: ldm.models.autoencoder.AutoencoderKL_Diffusion
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: stable_diffusion/sd-v1-4.ckpt
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1,2,4,4] #num_down=len(ch_mult)-1
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          num_groups: 32
        lossconfig:
          target: torch.nn.Identity
    
    hdmap_config:
      target: ldm.models.autoencoder.AutoencoderKL_Diffusion
      params:
        embed_dim: 4
        monitor: "val/rec_loss"
        ckpt_path: 
        ddconfig:
          double_z: True
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult: [1,2,4,4]
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
          num_groups: 32
        lossconfig:
          target: torch.nn.Identity
    box_config:
      target: ldm.models.autoencoder.Fourier_Embedding
      params:
        in_channels: 16
        ch: [256,512,768]
        context_dims: 768
        sigma: 1
        trainable: True

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 1
    wrap: False
    num_workers: 2
    train:
      target: data.video_dataloader_first_stage.dataloader
      params:
        cfg:
          version: v1.0-mini
          dataroot: /storage/group/4dvlab/datasets/nuScenes/mini
          img_size: [256,128]
        num_boxes: 70
        movie_len: 5
        split_name: train
        cond_stage_config: 
          target: ldm.models.autoencoder.FrozenCLIPTextEmbedder
    validation:
      target: data.video_dataloader_first_stage.dataloader
      params:
        cfg:
          version: v1.0-mini
          dataroot: /storage/group/4dvlab/datasets/nuScenes/mini
          img_size: [256,128]
        num_boxes: 70
        movie_len: 5
        split_name: val
        cond_stage_config: 
          target: ldm.models.autoencoder.FrozenCLIPTextEmbedder


lightning:
  callbacks:
    video_logger:
      target: main.VideoLogger
      params:
        batch_frequency: 1000
        max_videos: 8
        fps: 5
        increase_log_steps: False

  trainer:
    benchmark: True
    gpus: 0,

    